name: Matrix Strategy Testing example

on:
  push:
  workflow_dispatch:

jobs:
  matrix-strategy-testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11,3.12]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test Python Version
        run: python --version
      
