name: Call python workflow

on:
  push:
  workflow_dispatch:

jobs:
  calling-working:
    uses: kunals-repo/repo1/.github/workflows/python-reusable.yml@main
    with:
      python_version: "3.10"
      script_path: "app.py"
      
